<a href="https://colab.research.google.com/github/jouninLRMD/lrmercadod_academic/blob/master/LuisMercado_JuanDavid_RogerMunera_Reto10_(3)_(1)_(3)_(1)_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Reto 10.**
Re conectados.

Luís mercado

Juan David

Roger A. Múnera P

Importación de Numpy, Pandas y archivo homicide.

In [ ]:
import numpy as np
import pandas as pd
#Data import

df=pd.read_csv('/content/Homicide.csv')

In [ ]:
df.info()  # Noción primaria de la naturaleza de los datos.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 638454 entries, 0 to 638453
Data columns (total 24 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Record ID              638454 non-null  int64
 1   Agency Code            638454 non-null  object
 2   Agency Name            638454 non-null  object
 3   Agency Type            638454 non-null  object
 4   City                   638454 non-null  object
 5   State                  638454 non-null  object
 6   Year                   638454 non-null  int64
 7   Month                  638454 non-null  object
 8   Incident               638454 non-null  int64
 9   Crime Type             638454 non-null  object
 10  Crime Solved           638454 non-null  object
 11  Victim Sex             638454 non-null  object
 12  Victim Age             638454 non-null  int64
 13  Victim Race            638454 non-null  object
 14  Victim Ethnicity       638454 non-null  object
 15  Perpetrator Sex        638454 non-null  object
 16  Perpetrator Age        638454 non-null  object
 17  Perpetrator Race       638454 non-null  object
 18  Perpetrator Ethnicity  638454 non-null  object
 19  Relationship           638454 non-null  object
 20  Weapon                 638454 non-null  object
 21  Victim Count           638454 non-null  int64
 22  Perpetrator Count      638454 non-null  int64
 23  Record Source          638454 non-null  object
dtypes: int64(6), object(18)
memory usage: 116.9+ MB

El FBI lo contrata para realizar un proceso de análisis exploratorio científico sobre un histórico de homicidios reales en Estados Unidos, del cual desea conocer la siguiente información:

**1. Listar las cinco primeras ciudades con el mayor número de agencias.**

In [ ]:
df['Agency Type'].value_counts().sort_values(ascending=False)

Municipal Police    493026
Sheriff             105322
County Police        22693
State Police         14235
Special Police        2889
Regional Police        235
Tribal Police           54
Name: Agency Type, dtype: int64

In [ ]:
df[['Agency Type','City']].value_counts().sort_values(ascending=False)

Agency Type       City
Municipal Police  Los Angeles    38907
                  New York       38416
                  Cook           22279
                  Wayne          19321
                  Harris         13634
                                 ...
Sheriff           Rawlins            1
                  Red Lake           1
Municipal Police  Renville           1
Sheriff           Trigg              1
Municipal Police  Winneshiek         1
Length: 3946, dtype: int64

In [ ]:
df[['City','Agency Type']].value_counts().sort_values(ascending=False)

City            Agency Type
Los Angeles     Municipal Police    38907
New York        Municipal Police    38416
Cook            Municipal Police    22279
Wayne           Municipal Police    19321
Harris          Municipal Police    13634
                                    ...
San Bernardino  State Police            1
Chariton        Sheriff                 1
Kanawha         Special Police          1
Alleghany       State Police            1
Hendry          Tribal Police           1
Length: 3946, dtype: int64

**2. De los tipos de agencia, determinar las de tipo Sheriff y mostrar el nombre.**

In [ ]:
df[['Agency Name','Agency Type']]

            Agency Name       Agency Type
0             Anchorage  Municipal Police
1             Anchorage  Municipal Police
2             Anchorage  Municipal Police
3             Anchorage  Municipal Police
4             Anchorage  Municipal Police
...                 ...               ...
638449      Park County           Sheriff
638450  Sheridan County           Sheriff
638451         Sheridan  Municipal Police
638452  Sublette County           Sheriff
638453     Rock Springs  Municipal Police

[638454 rows x 2 columns]

In [ ]:

df[df['Agency Type']=='Sheriff']

,Record ID,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,...,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source
47,48,AL00100,Jefferson,Sheriff,Jefferson,Alabama,1980,February,1,Murder or Manslaughter,...,Unknown,Male,43,Black,Unknown,Neighbor,Rifle,0,0,FBI
48,49,AL00100,Jefferson,Sheriff,Jefferson,Alabama,1980,March,1,Murder or Manslaughter,...,Unknown,Female,38,White,Unknown,Husband,Shotgun,0,0,FBI
49,50,AL00100,Jefferson,Sheriff,Jefferson,Alabama,1980,April,1,Murder or Manslaughter,...,Unknown,Male,66,Black,Unknown,Acquaintance,Handgun,0,0,FBI
50,51,AL00100,Jefferson,Sheriff,Jefferson,Alabama,1980,May,1,Murder or Manslaughter,...,Unknown,Male,40,White,Unknown,Stranger,Handgun,0,0,FBI
51,52,AL00100,Jefferson,Sheriff,Jefferson,Alabama,1980,June,1,Murder or Manslaughter,...,Unknown,Female,23,White,Unknown,Husband,Handgun,0,0,FBI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
638445,638446,WY01200,Lincoln County,Sheriff,Lincoln,Wyoming,2014,December,1,Murder or Manslaughter,...,Unknown,Male,26,White,Unknown,Acquaintance,Handgun,0,0,FBI
638446,638447,WY01300,Natrona County,Sheriff,Natrona,Wyoming,2014,September,1,Murder or Manslaughter,...,Not Hispanic,Male,48,White,Not Hispanic,Mother,Handgun,0,0,FBI
638449,638450,WY01500,Park County,Sheriff,Park,Wyoming,2014,January,1,Murder or Manslaughter,...,Hispanic,Unknown,0,Unknown,Unknown,Unknown,Handgun,0,0,FBI
638450,638451,WY01700,Sheridan County,Sheriff,Sheridan,Wyoming,2014,June,1,Murder or Manslaughter,...,Unknown,Male,57,White,Unknown,Acquaintance,Handgun,0,0,FBI
638452,638453,WY01800,Sublette County,Sheriff,Sublette,Wyoming,2014,December,1,Murder or Manslaughter,...,Not Hispanic,Male,31,White,Not Hispanic,Stranger,Knife,0,1,FBI

**3. Listar los estados más afectados por crímenes perpetrados por mujeres.**

In [ ]:
df[['State','Perpetrator Sex']] #Estados y sexo predadores.

          State Perpetrator Sex
0        Alaska            Male
1        Alaska            Male
2        Alaska         Unknown
3        Alaska            Male
4        Alaska         Unknown
...         ...             ...
638449  Wyoming         Unknown
638450  Wyoming            Male
638451  Wyoming          Female
638452  Wyoming            Male
638453  Wyoming          Female

[638454 rows x 2 columns]

In [ ]:
df[df['Perpetrator Sex']=='Female'] #Predadores femenimos

,Record ID,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,...,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source
15,16,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,August,3,Murder or Manslaughter,...,Unknown,Female,29,Black,Unknown,Ex-Husband,Handgun,0,0,FBI
27,28,AKASP00,Alaska State Police,State Police,Juneau,Alaska,1980,February,2,Murder or Manslaughter,...,Unknown,Female,28,Native American/Alaska Native,Unknown,Husband,Handgun,0,0,FBI
28,29,AKASP00,Alaska State Police,State Police,Juneau,Alaska,1980,February,3,Murder or Manslaughter,...,Unknown,Female,36,Native American/Alaska Native,Unknown,Brother,Rifle,0,0,FBI
46,47,AKASP00,Alaska State Police,State Police,Juneau,Alaska,1980,December,2,Manslaughter by Negligence,...,Unknown,Female,27,Native American/Alaska Native,Unknown,Husband,Rifle,0,0,FBI
48,49,AL00100,Jefferson,Sheriff,Jefferson,Alabama,1980,March,1,Murder or Manslaughter,...,Unknown,Female,38,White,Unknown,Husband,Shotgun,0,0,FBI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
638433,638434,WVWSP53,State Police: Upperglade,State Police,Webster,West Virginia,2014,March,1,Murder or Manslaughter,...,Unknown,Female,30,White,Unknown,Friend,Unknown,0,0,FBI
638434,638435,WVWSP55,State Police: Welch,State Police,McDowell,West Virginia,2014,October,1,Murder or Manslaughter,...,Unknown,Female,35,White,Unknown,Unknown,Firearm,1,2,FBI
638435,638436,WVWSP55,State Police: Welch,State Police,McDowell,West Virginia,2014,October,1,Murder or Manslaughter,...,Unknown,Female,35,White,Unknown,Unknown,Firearm,1,2,FBI
638451,638452,WY01701,Sheridan,Municipal Police,Sheridan,Wyoming,2014,September,1,Murder or Manslaughter,...,Unknown,Female,22,Asian/Pacific Islander,Unknown,Daughter,Suffocation,0,0,FBI
638453,638454,WY01902,Rock Springs,Municipal Police,Sweetwater,Wyoming,2014,September,1,Murder or Manslaughter,...,Not Hispanic,Female,24,White,Not Hispanic,Daughter,Blunt Object,0,1,FBI

**4. Listar los estados más afectados por crímenes perpetrados por hombres.**

In [ ]:
df[df['Perpetrator Sex']=='Male']#Predadores masculinos.

,Record ID,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,...,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source
0,1,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,January,1,Murder or Manslaughter,...,Unknown,Male,15,Native American/Alaska Native,Unknown,Acquaintance,Blunt Object,0,0,FBI
1,2,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,March,1,Murder or Manslaughter,...,Unknown,Male,42,White,Unknown,Acquaintance,Strangulation,0,0,FBI
3,4,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,April,1,Murder or Manslaughter,...,Unknown,Male,42,White,Unknown,Acquaintance,Strangulation,0,0,FBI
5,6,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,May,1,Murder or Manslaughter,...,Unknown,Male,36,White,Unknown,Acquaintance,Rifle,0,0,FBI
6,7,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,May,2,Murder or Manslaughter,...,Unknown,Male,27,Black,Unknown,Wife,Knife,0,0,FBI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
638446,638447,WY01300,Natrona County,Sheriff,Natrona,Wyoming,2014,September,1,Murder or Manslaughter,...,Not Hispanic,Male,48,White,Not Hispanic,Mother,Handgun,0,0,FBI
638447,638448,WY01301,Casper,Municipal Police,Natrona,Wyoming,2014,June,1,Murder or Manslaughter,...,Not Hispanic,Male,22,White,Unknown,Girlfriend,Handgun,0,0,FBI
638448,638449,WY01301,Casper,Municipal Police,Natrona,Wyoming,2014,August,1,Murder or Manslaughter,...,Unknown,Male,67,Black,Unknown,Friend,Firearm,0,0,FBI
638450,638451,WY01700,Sheridan County,Sheriff,Sheridan,Wyoming,2014,June,1,Murder or Manslaughter,...,Unknown,Male,57,White,Unknown,Acquaintance,Handgun,0,0,FBI
638452,638453,WY01800,Sublette County,Sheriff,Sublette,Wyoming,2014,December,1,Murder or Manslaughter,...,Not Hispanic,Male,31,White,Not Hispanic,Stranger,Knife,0,1,FBI

**5. Determinar el número exacto de crímenes hechos por mujeres de raza Asian/Pacific Islander.**

In [ ]:
df[df['Perpetrator Race']=='Asian/Pacific Islander']#Perpetradores Asian/Pacific Islander

,Record ID,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,...,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source
31,32,AKASP00,Alaska State Police,State Police,Juneau,Alaska,1980,June,1,Manslaughter by Negligence,...,Unknown,Male,7,Asian/Pacific Islander,Unknown,Sister,Rifle,0,0,FBI
772,773,AR07501,Dardanelle,Municipal Police,Yell,Arkansas,1980,June,1,Murder or Manslaughter,...,Unknown,Male,46,Asian/Pacific Islander,Unknown,Son,Rifle,0,0,FBI
1315,1316,CA00800,Del Norte,Sheriff,Del Norte,California,1980,January,1,Murder or Manslaughter,...,Unknown,Male,29,Asian/Pacific Islander,Unknown,Acquaintance,Knife,0,2,FBI
1554,1555,CA01503,Delano,Municipal Police,Kern,California,1980,August,2,Murder or Manslaughter,...,Not Hispanic,Male,24,Asian/Pacific Islander,Not Hispanic,Acquaintance,Handgun,0,0,FBI
1569,1570,CA01801,Susanville,Municipal Police,Lassen,California,1980,March,1,Murder or Manslaughter,...,Unknown,Male,19,Asian/Pacific Islander,Unknown,Unknown,Knife,0,0,FBI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
638191,638192,WASPD00,Seattle,Municipal Police,King,Washington,2014,October,2,Murder or Manslaughter,...,Unknown,Male,78,Asian/Pacific Islander,Unknown,Daughter,Handgun,1,0,FBI
638274,638275,WIMPD00,Milwaukee,Municipal Police,Milwaukee,Wisconsin,2014,July,8,Murder or Manslaughter,...,Unknown,Male,23,Asian/Pacific Islander,Unknown,Acquaintance,Handgun,1,0,FBI
638282,638283,WIMPD00,Milwaukee,Municipal Police,Milwaukee,Wisconsin,2014,February,3,Murder or Manslaughter,...,Unknown,Male,38,Asian/Pacific Islander,Unknown,Acquaintance,Handgun,0,0,FBI
638322,638323,WIMPD00,Milwaukee,Municipal Police,Milwaukee,Wisconsin,2014,July,8,Murder or Manslaughter,...,Unknown,Male,23,Asian/Pacific Islander,Unknown,Acquaintance,Handgun,1,0,FBI
638451,638452,WY01701,Sheridan,Municipal Police,Sheridan,Wyoming,2014,September,1,Murder or Manslaughter,...,Unknown,Female,22,Asian/Pacific Islander,Unknown,Daughter,Suffocation,0,0,FBI

**6. Determinar la raza más criminal.**

In [ ]:
df['Perpetrator Race'].value_counts().sort_values(ascending=False) #Raza más criminal

White                            218243
Black                            214516
Unknown                          196047
Asian/Pacific Islander             6046
Native American/Alaska Native      3602
Name: Perpetrator Race, dtype: int64

**7. Determinar el número exacto de hispanos que han asesinado mediante la estrangulación.**

In [ ]:
df[df['Perpetrator Ethnicity']=='Hispanic'].value_counts()

Record ID  Agency Code  Agency Name     Agency Type       City         State       Year  Month     Incident  Crime Type              Crime Solved  Victim Sex  Victim Age  Victim Race  Victim Ethnicity  Perpetrator Sex  Perpetrator Age  Perpetrator Race  Perpetrator Ethnicity  Relationship  Weapon        Victim Count  Perpetrator Count  Record Source
142        AL00102      Birmingham      Municipal Police  Jefferson    Alabama     1980  October   4         Murder or Manslaughter  Yes           Male        19          Black        Not Hispanic      Male             25               Black             Hispanic               Acquaintance  Handgun       0             0                  FBI              1
418410     CA01900      Los Angeles     Sheriff           Los Angeles  California  2001  January   9         Murder or Manslaughter  Yes           Male        38          Black        Not Hispanic      Male             41               White             Hispanic               Stranger      Handgun       0             0                  FBI              1
418415     CA01900      Los Angeles     Sheriff           Los Angeles  California  2001  February  4         Murder or Manslaughter  Yes           Female      42          White        Hispanic          Male             28               White             Hispanic               Wife          Blunt Object  0             0                  FBI              1
418416     CA01900      Los Angeles     Sheriff           Los Angeles  California  2001  February  5         Murder or Manslaughter  Yes           Female      18          White        Hispanic          Male             20               White             Hispanic               Girlfriend    Handgun       0             0                  FBI              1
418424     CA01900      Los Angeles     Sheriff           Los Angeles  California  2001  March     4         Murder or Manslaughter  Yes           Female      22          White        Hispanic          Male             23               White             Hispanic               Girlfriend    Handgun       0             0                  FBI              1
                                                                                                                                                                                                                                                                                                                                                                  ..
197405     TXSPD00      San Antonio     Municipal Police  Bexar        Texas       1989  November  4         Murder or Manslaughter  Yes           Male        23          White        Hispanic          Male             22               White             Hispanic               Unknown       Firearm       0             0                  FBI              1
197408     TXSPD00      San Antonio     Municipal Police  Bexar        Texas       1989  November  7         Murder or Manslaughter  Yes           Male        31          White        Hispanic          Female           0                White             Hispanic               Unknown       Firearm       0             1                  FBI              1
197409     TXSPD00      San Antonio     Municipal Police  Bexar        Texas       1989  November  8         Murder or Manslaughter  Yes           Male        30          White        Hispanic          Male             20               White             Hispanic               Unknown       Firearm       0             0                  FBI              1
197411     TXSPD00      San Antonio     Municipal Police  Bexar        Texas       1989  November  10        Murder or Manslaughter  Yes           Female      41          White        Hispanic          Male             42               White             Hispanic               Wife          Handgun       0             0                  FBI              1
638143     WA03215      Spokane Valley  Municipal Police  Spokane      Washington  2014  November  1         Murder or Manslaughter  Yes           Male        44          White        Not Hispanic      Male             32               White             Hispanic               Family        Handgun       1             0                  FBI              1
Length: 46872, dtype: int64

In [ ]:
df[['Perpetrator Ethnicity','Crime Type']].value_counts().sort_values(ascending=False) #Raza más criminal

Perpetrator Ethnicity  Crime Type
Unknown                Murder or Manslaughter        440814
Not Hispanic           Murder or Manslaughter        142354
Hispanic               Murder or Manslaughter         46170
Unknown                Manslaughter by Negligence      5596
Not Hispanic           Manslaughter by Negligence      2818
Hispanic               Manslaughter by Negligence       702
dtype: int64

In [ ]:
df['Perpetrator Race'].value_counts().sort_values(ascending=False) #Raza más criminal

White                            218243
Black                            214516
Unknown                          196047
Asian/Pacific Islander             6046
Native American/Alaska Native      3602
Name: Perpetrator Race, dtype: int64

**8. Determinar el tipo de relación más peligrosa, el cual comete más homicidios con armas de tipo Shotgun=escopeta.**

In [ ]:
df[['Relationship','Weapon']] #Relación y armas en el suceso.

        Relationship         Weapon
0       Acquaintance   Blunt Object
1       Acquaintance  Strangulation
2            Unknown        Unknown
3       Acquaintance  Strangulation
4            Unknown        Unknown
...              ...            ...
638449       Unknown        Handgun
638450  Acquaintance        Handgun
638451      Daughter    Suffocation
638452      Stranger          Knife
638453      Daughter   Blunt Object

[638454 rows x 2 columns]

In [ ]:
df[df['Weapon']=='Shotgun']

,Record ID,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,...,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source
11,12,AK00101,Anchorage,Municipal Police,Anchorage,Alaska,1980,July,2,Murder or Manslaughter,...,Unknown,Male,49,White,Unknown,Stranger,Shotgun,0,0,FBI
29,30,AKASP00,Alaska State Police,State Police,Juneau,Alaska,1980,April,1,Murder or Manslaughter,...,Unknown,Male,61,Native American/Alaska Native,Unknown,Unknown,Shotgun,0,0,FBI
48,49,AL00100,Jefferson,Sheriff,Jefferson,Alabama,1980,March,1,Murder or Manslaughter,...,Unknown,Female,38,White,Unknown,Husband,Shotgun,0,0,FBI
60,61,AL00100,Jefferson,Sheriff,Jefferson,Alabama,1980,November,1,Manslaughter by Negligence,...,Not Hispanic,Male,15,White,Not Hispanic,Friend,Shotgun,0,0,FBI
67,68,AL00101,Bessemer,Municipal Police,Jefferson,Alabama,1980,June,1,Murder or Manslaughter,...,Not Hispanic,Male,28,Black,Not Hispanic,Acquaintance,Shotgun,0,0,FBI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
638196,638197,WI00300,Barron County,Sheriff,Barron,Wisconsin,2014,March,1,Murder or Manslaughter,...,Unknown,Male,34,White,Unknown,Acquaintance,Shotgun,0,2,FBI
638220,638221,WI01801,Eau Claire,Municipal Police,Eau Claire,Wisconsin,2014,August,1,Murder or Manslaughter,...,Unknown,Male,60,White,Unknown,Wife,Shotgun,0,0,FBI
638411,638412,WV03400,Nicholas County,Sheriff,Nicholas,West Virginia,2014,December,1,Murder or Manslaughter,...,Unknown,Male,59,White,Unknown,Acquaintance,Shotgun,0,0,FBI
638423,638424,WVWSP01,State Police: Beckley,State Police,Raleigh,West Virginia,2014,September,1,Murder or Manslaughter,...,Unknown,Male,60,White,Unknown,Wife,Shotgun,0,0,FBI
638442,638443,WY01100,Laramie County,Sheriff,Laramie,Wyoming,2014,July,1,Murder or Manslaughter,...,Not Hispanic,Male,61,White,Not Hispanic,Wife,Shotgun,0,0,FBI

**9. ¿Cuál es el sexo de quienes más homicidios han cometido con Veneno =Poison.**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 638454 entries, 0 to 638453
Data columns (total 24 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Record ID              638454 non-null  int64
 1   Agency Code            638454 non-null  object
 2   Agency Name            638454 non-null  object
 3   Agency Type            638454 non-null  object
 4   City                   638454 non-null  object
 5   State                  638454 non-null  object
 6   Year                   638454 non-null  int64
 7   Month                  638454 non-null  object
 8   Incident               638454 non-null  int64
 9   Crime Type             638454 non-null  object
 10  Crime Solved           638454 non-null  object
 11  Victim Sex             638454 non-null  object
 12  Victim Age             638454 non-null  int64
 13  Victim Race            638454 non-null  object
 14  Victim Ethnicity       638454 non-null  object
 15  Perpetrator Sex        638454 non-null  object
 16  Perpetrator Age        638454 non-null  object
 17  Perpetrator Race       638454 non-null  object
 18  Perpetrator Ethnicity  638454 non-null  object
 19  Relationship           638454 non-null  object
 20  Weapon                 638454 non-null  object
 21  Victim Count           638454 non-null  int64
 22  Perpetrator Count      638454 non-null  int64
 23  Record Source          638454 non-null  object
dtypes: int64(6), object(18)
memory usage: 116.9+ MB

In [ ]:
df[df['Weapon']=='Poison']

,Record ID,Agency Code,Agency Name,Agency Type,City,State,Year,Month,Incident,Crime Type,...,Victim Ethnicity,Perpetrator Sex,Perpetrator Age,Perpetrator Race,Perpetrator Ethnicity,Relationship,Weapon,Victim Count,Perpetrator Count,Record Source
2950,2951,CA01942,Los Angeles,Municipal Police,Los Angeles,California,1980,October,49,Murder or Manslaughter,...,Not Hispanic,Unknown,0,Unknown,Unknown,Unknown,Poison,0,0,FBI
4072,4073,CA03711,San Diego,Municipal Police,San Diego,California,1980,October,1,Murder or Manslaughter,...,Not Hispanic,Unknown,0,Unknown,Unknown,Unknown,Poison,0,1,FBI
7208,7209,GAAPD00,Atlanta,Municipal Police,Fulton,Georgia,1980,December,7,Murder or Manslaughter,...,Not Hispanic,Unknown,0,Unknown,Unknown,Unknown,Poison,0,0,FBI
8268,8269,ILCPD00,Chicago,Municipal Police,Cook,Illinois,1980,July,71,Murder or Manslaughter,...,Unknown,Female,19,Black,Unknown,Daughter,Poison,0,0,FBI
9354,9355,KY026SP,State Police: Clay County,State Police,Clay,Kentucky,1980,December,6,Murder or Manslaughter,...,Not Hispanic,Female,26,White,Not Hispanic,Husband,Poison,0,0,FBI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
634694,634695,OK07300,Wagoner County,Sheriff,Wagoner,Oklahoma,2014,January,1,Murder or Manslaughter,...,Unknown,Female,59,White,Unknown,Acquaintance,Poison,1,0,FBI
634695,634696,OK07300,Wagoner County,Sheriff,Wagoner,Oklahoma,2014,January,1,Murder or Manslaughter,...,Unknown,Female,59,White,Unknown,Acquaintance,Poison,1,0,FBI
635073,635074,PA064SP,State Police: Wayne County,State Police,Wayne,Pennsylvania,2014,June,1,Murder or Manslaughter,...,Not Hispanic,Male,75,White,Not Hispanic,Wife,Poison,0,0,FBI
637636,637637,VA00800,Augusta County,Sheriff,Augusta,Virginia,2014,March,1,Murder or Manslaughter,...,Unknown,Male,65,White,Unknown,Wife,Poison,0,0,FBI
638063,638064,WA01800,Kitsap County,Sheriff,Kitsap,Washington,2014,March,1,Murder or Manslaughter,...,Unknown,Female,55,White,Unknown,Husband,Poison,0,0,FBI

In [ ]:
df[['Perpetrator Race','Weapon']]

                     Perpetrator Race         Weapon
0       Native American/Alaska Native   Blunt Object
1                               White  Strangulation
2                             Unknown        Unknown
3                               White  Strangulation
4                             Unknown        Unknown
...                               ...            ...
638449                        Unknown        Handgun
638450                          White        Handgun
638451         Asian/Pacific Islander    Suffocation
638452                          White          Knife
638453                          White   Blunt Object

[638454 rows x 2 columns]

**10. ¿Cuántos asesinos de raza negra atrapó el FBI?**

In [ ]:
df[df['Perpetrator Race']=='Black'].count()

Record ID                1575
Agency Code              1575
Agency Name              1575
Agency Type              1575
City                     1575
State                    1575
Year                     1575
Month                    1575
Incident                 1575
Crime Type               1575
Crime Solved             1575
Victim Sex               1575
Victim Age               1575
Victim Race              1575
Victim Ethnicity         1575
Perpetrator Sex          1575
Perpetrator Age          1575
Perpetrator Race         1575
Perpetrator Ethnicity    1575
Relationship             1575
Weapon                   1575
Victim Count             1575
Perpetrator Count        1575
Record Source            1575
dtype: int64

**11. ¿Cuántas victimas de tipo hispanas han muerto y por cual tipo de medio (arma blanca, arma de fuego, etc).**

In [ ]:
df['Weapon'].unique()
df['Victim Ethnicity']=='Hispanic'
df.groupby(['Victim Ethnicity', 'Weapon'])

0       False
1       False
2       False
3       False
4       False
        ...
5897    False
5898     True
5899     True
5900    False
5901    False
Name: Victim Ethnicity, Length: 5902, dtype: bool

**12. ¿Cuál ha sido el asesino más viejo?**

In [ ]:
df['Perpetrator Age'].max()

**13. ¿Cuál ha sido el asesino más jóven?**

In [ ]:
df['Perpetrator Age'].min()

**14. ¿Cuál es el total de homicidios desde el año 1995 hasta el año 2000 (ADVERTENCIA: META CONSULTAS DE TIPO KILLER)?**

In [ ]:
df[(df['Year']>=1995) & (df['Year']<=2000)]

**15. ¿Cuál es el total de homicidiosdesde el año 1995 hasta el año 2000 perpetrados por hombres de raza negra por sofocación=suffocation?**

In [ ]:
df[(df['Year']>=1995) & (df['Year']=<2000) & (df['Weapon']=='Suffocation') & (df['Perpetrator Race']=='Black')]

**16. Determinar los homicidios anteriores a 1980 perpetrados por hombres del estado de Alaska de raza negra.**

In [ ]:
df_year = df[df["Year"]<=1980]
df_year[(df_year["Perpetrator Race"]=="Black")&(df_year['Perpetrator Sex']=='Male')&(df_year["State"]=="Alaska")]

**17. Determinar los homicidios de la policia municipal de la ciudad de New York los cuales hayan sido por relaciones de tipo Ex-Wife y, además, que su modo haya sido Estrangulación=Strangulation.**

In [ ]:
df[(df['Agency Type']=='Municipal Police') & (df['City']=='New York') & (df['Relationship']=='Ex-Wife')&(df['Weapon']=='Strangulation')]

**18. Listar todos los homicidios que hayan ocurrido desde 1980 hasta 1970 en el estado de Illinois de los cuales el grupo étnico de la víctima no es hispano= Not Hispanic y la relación con el asesino fue de amigos=Friends y el arma utilizada fue una escopeta=Shotgun.**

In [ ]:
df[(df['Year']>=1995) & (df['Year']<=2000) & (df['Victim Ethnicity']=='Not Hispanic') & (df['Weapon']=='Shotgun') & (df['Relationship']=='Friends')]